### ISSUE TITLE
"gatsby-source-craft" threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by thejoshsmith** [craftcms/gatsby-source-craft#45]
### Description
I'm frequently encountering the following error on Gatsby Cloud when making changes in CraftCMS:

```
"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Cannot read property 'map' of null

488 |         // Create the sourcing node events
  489 |         const nodeEvents = [
> 490 |             ...updatedNodes.map(entry => {
      |                             ^
  491 |                 return {
  492 |                     eventName: 'UPDATE',
  493 |                     remoteTypeName: entry.nodeType,
```
The only difference from a normal setup is that I have registered a custom source node type to support Craft Commerce Products by doing the following:
```
Event::on(
    SourceNodes::class,
    SourceNodes::EVENT_REGISTER_SOURCE_NODE_TYPES,
    function (RegisterSourceNodeTypesEvent $event) {
        $event->types[] = [
            'node' => 'product',
            'list' => 'products',
            'filterArgument' => 'type',
            'filterTypeExpression' => '(.+)_Product',
            'targetInterface' => ProductInterface::getName(),
        ];
    }
);
```

The build succeeds if I clear the cache and perform a fresh build from Gatsby Cloud (which is not an ideal solution for my client!).

I'll have a good dig through over the weekend and see if I can nail down what's actually causing this error.

### Steps to reproduce

Not sure at the moment, it seems to happen after making a few changes to entries after a fresh build.

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4.10
- Database driver & version: MySQL 8.0.21
- Plugins & versions:
  - Amazon SES - 1.3.3
  - Craft Commerce - 3.3.2
  - Gatsby Helper - 1.0.3
  - Mailchimp Subscribe - 3.0.3
  - MatrixMate 1.2.7
  - Redactor - 2.8.7
  - SEOmatic - 3.3.42
  - Stripe for Craft Commerce - 2.3.2.1
  - Super Table - 2.6.8

![Screen Shot 2021-07-01 at 8 58 23 PM](https://user-images.githubusercontent.com/5515179/124096863-1916f900-daaf-11eb-9cac-0f33bee7d807.png)

**Comment by andris-sevcenko** [comment]
Gatsby Helper _always_ returns an array there (https://github.com/craftcms/gatsby-helper/blob/main/src/gql/resolvers/UpdatedNode.php#L29).

When you next hit this issue, can you check the Craft logs for anything suspicious? Maybe there's a Craft error that causes it to bail out without a proper response.

**Comment by thejoshsmith** [comment]
Thanks @andris-sevcenko, I'll check it out and post my findings here.

**Comment by thejoshsmith** [comment]
Update—Found these errors repeated quite a bit in my log file:

```
2021-07-05 02:35:42 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: craft\commerce\elements\Product::productTypeId in /vendor/yiisoft/yii2/base/Component.php:155
2021-07-05 02:35:42 [-][-][-][error][GraphQL\Error\Error] String cannot represent value: instance of nystudio107\seomatic\models\MetaBundle
```

**Comment by andris-sevcenko** [comment]
Is there a stack trace for either of those errors? If not, can you enable `devMode` and re-create those errors to get a stack trace?

**Comment by thejoshsmith** [comment]
Stack trace for the first error is:

```
Stack trace:
#0 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/base/Element.php(1533): yii\base\Component->__get()
#1 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/gql/base/ObjectType.php(73): craft\base\Element->__get()
#2 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/gql/types/elements/Element.php(54): craft\gql\base\ObjectType->resolve()
#3 /opt/bitnami/apache/htdocs/vendor/craftcms/commerce/src/gql/types/elements/Product.php(48): craft\gql\types\elements\Element->resolve()
#4 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/gql/base/ObjectType.php(47): craft\commerce\gql\types\elements\Product->resolve()
#5 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(624): craft\gql\base\ObjectType->resolveWithDirectives()
#6 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(550): GraphQL\Executor\ReferenceExecutor->resolveFieldValueOrError()
#7 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1196): GraphQL\Executor\ReferenceExecutor->resolveField()
#8 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1146): GraphQL\Executor\ReferenceExecutor->executeFields()
#9 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1107): GraphQL\Executor\ReferenceExecutor->collectAndExecuteSubfields()
#10 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(975): GraphQL\Executor\ReferenceExecutor->completeObjectValue()
#11 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(790): GraphQL\Executor\ReferenceExecutor->completeAbstractValue()
#12 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(655): GraphQL\Executor\ReferenceExecutor->completeValue()
#13 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(888): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError()
#14 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(762): GraphQL\Executor\ReferenceExecutor->completeListValue()
#15 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(655): GraphQL\Executor\ReferenceExecutor->completeValue()
#16 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError()
#17 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1196): GraphQL\Executor\ReferenceExecutor->resolveField()
#18 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(264): GraphQL\Executor\ReferenceExecutor->executeFields()
#19 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\Executor\ReferenceExecutor->executeOperation()
#20 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\Executor\ReferenceExecutor->doExecute()
#21 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\Executor\Executor::promiseToExecute()
#22 /opt/bitnami/apache/htdocs/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\GraphQL::promiseToExecute()
#23 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/services/Gql.php(545): GraphQL\GraphQL::executeQuery()
#24 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/controllers/GraphqlController.php(172): craft\services\Gql->executeQuery()
#25 [internal function]: craft\controllers\GraphqlController->actionApi()
#26 /opt/bitnami/apache/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#27 /opt/bitnami/apache/htdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#28 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#29 /opt/bitnami/apache/htdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#30 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction()
#31 /opt/bitnami/apache/htdocs/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#32 /opt/bitnami/apache/htdocs/vendor/craftcms/cms/src/web/Application.php(263): yii\web\Application->handleRequest()
#33 /opt/bitnami/apache/htdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#34 /opt/bitnami/apache/htdocs/web/index.php(22): yii\base\Application->run()
#35 {main}
```

PR here: https://github.com/craftcms/commerce/pull/2248

**Comment by thejoshsmith** [comment]
No stack trace for the second error. Have now enabled `devMode` so will see what comes through.

**Comment by andris-sevcenko** [comment]
If you add the changes to the Product, does that resolve the issue?

If you're still hitting the SEOMatic issue, you might need to use custom fragments to resolve that. We're working on a more prominent guide of when and why to use custom fragments guide.

**Comment by thejoshsmith** [comment]
Hey @andris-sevcenko, just an update on this. I did a lot of digging on my local setup and I think I've found the cause of this issue!

Basically, whenever an order is created or updated, the following error will occur when the site next tries to build:
```
"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Missing Gatsby node definition for remote type Element

  510 |         }
  511 |         // And source, if needed
> 512 |         await sourceNodeChanges(config, { nodeEvents });
      |         ^
  513 |     }
  514 |     await cache.set(`CRAFT_CONFIG_VERSION`, remoteConfigVersion);
  515 |     await cache.set(`CRAFT_LAST_CONTENT_UPDATE`, remoteContentUpdateTime);

File: node_modules/gatsby-source-craft/gatsby-node.js:512:9

  Error: Missing Gatsby node definition for remote type Element

  - node-definition-helpers.ts:46 Object.getGatsbyNodeDefinition
    [website]/[gatsby-graphql-source-toolkit]/src/source-nodes/utils/node-definition-helpers.ts:46:11

  - fetch-nodes.ts:37 fetchNodesById
    [website]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/fetch-nodes.ts:37:26

  - fetchNodesById.next

  - fetch-nodes.ts:19 Object.fetchNonNullishNodesById
    [website]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/fetch-nodes.ts:19:20

  - fetchNonNullishNodesById.next

  - create-nodes.ts:13 Object.createNodes
    [website]/[gatsby-graphql-source-toolkit]/src/source-nodes/node-actions/create-nodes.ts:13:20

  - source-node-changes.ts:31 sourceNodeChanges
    [website]/[gatsby-graphql-source-toolkit]/src/source-nodes/source-node-changes.ts:31:21

  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5

  - gatsby-node.js:512 Object.exports.sourceNodes
    [website]/[gatsby-source-craft]/gatsby-node.js:512:9

  - api-runner-node.js:429 runAPI
    [website]/[gatsby]/src/utils/api-runner-node.js:429:16


not finished source and transform nodes - 2.492s
```

If I clear the Gatsby cache and rebuild then it's fine. 

I've uploaded a copy of the `web.log` file that was generated during the build. There's a few order queries at the end (presumably just before the build fails).

[web.log.zip](https://github.com/craftcms/gatsby-source-craft/files/6916408/web.log.zip)

Any pointers on how to resolve this would be great. If you need any more info from me just let me know 😄

**Comment by andris-sevcenko** [comment]
Ah, so the orders are the culprit.

I'm guessing you don't want to expose Order information for the Gatsby sites, so you should add them to the ignored types: https://github.com/craftcms/gatsby-helper/blob/main/src/services/Deltas.php#L49

In essence, if you have a custom element type (or, rather, one that is not covered by the helper plugin by default), you should either register the custom source node type for it or tell the helper plugin to stop triggering updates on that type of element save.

I think that should cover it. Can you, please, try this out and let me know how it goes?

**Comment by thejoshsmith** [comment]
Yep, that's done the trick. Fantastic, thanks so much for your assistance @andris-sevcenko 🎉 

> I'm guessing you don't want to expose Order information for the Gatsby sites, so you should add them to the ignored types: https://github.com/craftcms/gatsby-helper/blob/main/src/services/Deltas.php#L49

Yeah that's right, no order information (at this stage anyway). I don't think Commerce exposes Orders via GraphQL at the moment so it may have to be through a custom API/ element API.

Closing now 😄
